postgresql:
  enabled: true
  postgresqlUsername: "db_user"
  postgresqlPassword: "Zu0yAx"
  postgresqlDatabase: "Products"
  identityServerDatabase: "IdentityServer"
  service:
    port: "5432"
  image:
    tag: "latest"
  persistence:
    size: 1Gi   
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 10s
      
productApi:
  image:
    repository: "stilux/product-api"
    pullPolicy: Always
  replicaCount: 1
  configPath: "/app/config"
  logLevel: "Information"
  allowedHosts: "*"
  cache:
    enabled: true
    sizeLimit: 100    
  
authServer:
  image:
    repository: "stilux/auth-server"
    pullPolicy: Always
  replicaCount: 1
  configPath: "/app/config"
  logLevel: "Information"
  allowedHosts: "*"
  
apiGateway:
  image:
    repository: "stilux/auth-api-gateway"
    pullPolicy: Always
  replicaCount: 1
  configPath: "/app/config"
  logLevel: "Information"
  allowedHosts: "*"
  
service:
  type: "ClusterIP"
  port: 80
  
ingress:
  enabled: true
  host: arch.homework  
  
log:  
  level: "Information"